import assert from "node:assert/strict"
import fs from "node:fs"
import os from "node:os"
import path from "node:path"
import test from "node:test"

import { Database } from "../js/database.js"
import { createHost } from "./host.js"

test("database executes persistent relational SQL", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-database-"))
  const file = path.join(directory, "data.db")
  const host = createHost()
  let database = Database.open(file, host)
  database.execute("CREATE TABLE users (id BIGINT PRIMARY KEY, name TEXT NOT NULL, score INT)")
  database.execute("INSERT INTO users VALUES (1, 'Ada', 9), (2, 'Linus', 7), (3, 'Grace', 10)")
  assert.deepEqual(database.execute("SELECT name FROM users WHERE score >= 9 ORDER BY name"), [["Ada"], ["Grace"]])
  assert.deepEqual(database.execute("SELECT COUNT(*), MAX(score) FROM users"), [[3n, 10]])
  database.close()
  database = Database.open(file, host)
  assert.deepEqual(database.execute("SELECT name FROM users WHERE id = 2"), [["Linus"]])
  database.close()
  fs.rmSync(directory, { recursive: true })
})

test("updates deletes and rollbacks preserve row versions", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-mvcc-"))
  const file = path.join(directory, "data.db")
  const database = Database.open(file, createHost())
  database.execute("CREATE TABLE accounts (id BIGINT PRIMARY KEY, balance INT NOT NULL)")
  database.execute("INSERT INTO accounts VALUES (1, 100), (2, 200)")
  database.execute("BEGIN")
  database.execute("UPDATE accounts SET balance = balance + 50 WHERE id = 1")
  database.execute("DELETE FROM accounts WHERE id = 2")
  database.execute("ROLLBACK")
  assert.deepEqual(database.execute("SELECT id, balance FROM accounts ORDER BY id"), [[1n, 100], [2n, 200]])
  database.execute("UPDATE accounts SET balance = 125 WHERE id = 1")
  database.execute("DELETE FROM accounts WHERE id = 2")
  assert.deepEqual(database.execute("SELECT id, balance FROM accounts"), [[1n, 125]])
  database.close()
  fs.rmSync(directory, { recursive: true })
})

test("primary unique not null and foreign keys reject invalid rows", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-constraints-"))
  const database = Database.open(path.join(directory, "data.db"), createHost())
  database.execute("CREATE TABLE users (id BIGINT PRIMARY KEY, email TEXT UNIQUE NOT NULL)")
  database.execute("CREATE TABLE orders (id BIGINT PRIMARY KEY, user_id BIGINT REFERENCES users(id))")
  database.execute("INSERT INTO users VALUES (1, 'ada@example.test')")
  assert.throws(() => database.execute("INSERT INTO users VALUES (2, 'ada@example.test')"), /Unique constraint/)
  assert.throws(() => database.execute("INSERT INTO users VALUES (3, NULL)"), /cannot be null/)
  assert.throws(() => database.execute("INSERT INTO orders VALUES (1, 99)"), /Foreign key/)
  database.execute("INSERT INTO orders VALUES (1, 1)")
  assert.throws(() => database.execute("DELETE FROM users WHERE id = 1"), /Delete restricted/)
  database.close()
  fs.rmSync(directory, { recursive: true })
})

test("joins limits aggregates and explain use the query pipeline", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-query-"))
  const database = Database.open(path.join(directory, "data.db"), createHost())
  database.execute("CREATE TABLE users (id BIGINT PRIMARY KEY, name TEXT NOT NULL)")
  database.execute("CREATE TABLE orders (id BIGINT PRIMARY KEY, user_id BIGINT NOT NULL, amount INT NOT NULL)")
  database.execute("INSERT INTO users VALUES (1, 'Ada'), (2, 'Grace')")
  database.execute("INSERT INTO orders VALUES (1, 1, 20), (2, 1, 30), (3, 2, 40)")
  assert.deepEqual(database.execute("SELECT u.name, o.amount FROM users AS u INNER JOIN orders AS o ON o.user_id = u.id ORDER BY o.amount DESC LIMIT 2"), [["Grace", 40], ["Ada", 30]])
  assert.match(database.execute("EXPLAIN SELECT name FROM users WHERE id = 1"), /IndexScan/)
  database.close()
  fs.rmSync(directory, { recursive: true })
})

test("rolled back DDL stays absent after restart", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-ddl-"))
  const file = path.join(directory, "data.db")
  const host = createHost()
  let database = Database.open(file, host)
  database.execute("BEGIN")
  database.execute("CREATE TABLE temporary_table (id BIGINT PRIMARY KEY)")
  database.execute("ROLLBACK")
  database.close()
  database = Database.open(file, host)
  assert.throws(() => database.execute("SELECT * FROM temporary_table"), /does not exist/)
  database.close()
  fs.rmSync(directory, { recursive: true })
})

test("secondary indexes rebuild from persisted heap rows", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-index-"))
  const file = path.join(directory, "data.db")
  const host = createHost()
  let database = Database.open(file, host)
  database.execute("CREATE TABLE people (id BIGINT PRIMARY KEY, email TEXT NOT NULL)")
  database.execute("CREATE UNIQUE INDEX people_email ON people(email)")
  database.execute("INSERT INTO people VALUES (1, 'one@test'), (2, 'two@test')")
  database.close()
  database = Database.open(file, host)
  assert.deepEqual(database.execute("SELECT id FROM people WHERE email = 'two@test'"), [[2n]])
  assert.match(database.execute("EXPLAIN SELECT id FROM people WHERE email = 'two@test'"), /people_email/)
  database.close()
  fs.rmSync(directory, { recursive: true })
})

test("database metrics expose storage transaction and query work", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mydb-stats-"))
  const database = Database.open(path.join(directory, "data.db"), createHost())
  database.execute("CREATE TABLE metric_values (id BIGINT PRIMARY KEY)")
  database.execute("INSERT INTO metric_values VALUES (1)")
  database.execute("SELECT * FROM metric_values")
  const stats = database.stats()
  assert.equal(stats.transactionsCommitted, 3)
  assert.equal(stats.queriesExecuted, 3)
  assert.ok(stats.pagesWritten > 0)
  assert.ok(stats.walFsyncs > 0)
  database.close()
  fs.rmSync(directory, { recursive: true })
})
